package com.demo.ssm.dao;

import com.demo.ssm.bean.Deptarment;
import com.demo.ssm.bean.DeptarmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptarmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    long countByExample(DeptarmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int deleteByExample(DeptarmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int insert(Deptarment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int insertSelective(Deptarment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    List<Deptarment> selectByExample(DeptarmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    Deptarment selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Deptarment record, @Param("example") DeptarmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Deptarment record, @Param("example") DeptarmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Deptarment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deptarment record);
}